apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
  labels: 
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template: 
    metadata:
      labels:
        app: postgres
    spec: 
      containers: 
        - name: postgres
          image: postgres:17-alpine
          ports:
          -  containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "workiez"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
