package workiez.workiez.service;

public enum ServiceName {

    MASON, ROOFER, ELECTRICIAN, PLUMBER,HVAC,
    COMPUTER_REPAIR, FURNITURE_REPAIR, TILE_SETTING, PLASTERING,
    CLEANING, TRANSPORT, PAINTING, WASTE_AND_ENVIRONMENTAL_SERVICES,
    PEST_CONTROL, CARPENTERS

}
