apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend-deployment
  labels:
    app: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-frontend
          image: indura08/workiez-project:angular-v4
          ports:
            - containerPort: 80

#kubectl exec -it angular-frontend -- nslookup spring-backend
